### ISSUE TITLE
Possible error in test

### ISSUE THREAD

**Issue by manuelelucchi** [let-unimi/liblet#7] opened 2020-05-04 10:08 UTC
In the file automaton_test.py there is a test (`test_transition_lt`) that's a bit strange, feels like there's been a copy-paste from the one above
![image](https://user-images.githubusercontent.com/17146198/80955131-fa5f9880-8dfe-11ea-8ab3-59c8aca3c547.png)

Shouldn't it be something like 
```python
def test_transition_lt(self):
        self.assetTrue(t1.__lt__(t2))
```
where `t1` and `t2` are previously defined transitions?

Regards,
Manuele

**Comment by mapio** [comment] 2020-05-04 12:37
It was a duplicate of the equality test for the string representation.

**Closed as completed** 2020-05-04 12:36 UTC
